apiVersion: apps/v1
kind: Deployment
metadata:
  name: agritech-deployment
  labels:
    app: agritech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agritech
  template:
    metadata:
      labels:
        app: agritech
      annotations:
        argocd-image-updater.argoproj.io/image-list: agritech=270368607340.dkr.ecr.ap-south-1.amazonaws.com/agritech-frontend
        argocd-image-updater.argoproj.io/agritech.update-strategy: latest
        argocd-image-updater.argoproj.io/agritech.allow-tags: regexp:^latest$
        argocd-image-updater.argoproj.io/agritech.pull-secret: ecr-credentials
    spec:
      imagePullSecrets:
        - name: ecr-credentials
      containers:
        - name: agritech
          image: 270368607340.dkr.ecr.ap-south-1.amazonaws.com/agritech-frontend:latest
          ports:
            - containerPort: 80
