apiVersion: apps/v1
kind: Deployment
metadata:
  name: agritech-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agritech
  template:
    metadata:
      labels:
        app: agritech
    spec:
      containers:
      - name: agritech
        image: IMAGE_TAG_PLACEHOLDER
        ports:
        - containerPort: 80
