apiVersion: apps/v1
kind: Deployment
metadata:
  name: agritech-deployment
  annotations:
    argocd-image-updater.argoproj.io/image-list: agritech=270368607340.dkr.ecr.ap-south-1.amazonaws.com/agritech-frontend
    argocd-image-updater.argoproj.io/agritech.update-strategy: newest-build
    argocd-image-updater.argoproj.io/agritech.pull-secret: secret:ecr-credentials
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agritech
  template:
    metadata:
      labels:
        app: agritech
    spec:
      containers:
      - name: agritech
        image: 270368607340.dkr.ecr.ap-south-1.amazonaws.com/agritech-frontend:latest
        ports:
        - containerPort: 80
