apiVersion: apps/v1
kind: Deployment
metadata:
  name: agritech-frontend
  labels:
    app: agritech-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agritech-frontend
  template:
    metadata:
      labels:
        app: agritech-frontend
    spec:
      containers:
      - name: agritech-frontend
        image: IMAGE_TAG_PLACEHOLDER
        ports:
        - containerPort: 80
        imagePullPolicy: Always
