apiVersion: apps/v1
kind: Deployment
metadata:
  name: agritech-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agritech
  template:
    metadata:
      labels:
        app: agritech
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: agritech
        image: 270368607340.dkr.ecr.ap-south-1.amazonaws.com/agritech-frontend:latest
        ports:
        - containerPort: 80
