apiVersion: v1
kind: Service
metadata:
  name: agritech-frontend-service
spec:
  selector:
    app: agritech-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
